jobs: 
      - script: >
          pipelineJob('Containers/jenkins-master') {
            def repo = 'https://github.com/liatrio/liatrio-jenkins.git'
            def script = 'Jenkinsfile.dev'
            description('Pipeline for $script in $repo')
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url(repo)
                    }
                    branches('productzero')
                    scriptPath(script)
                    extensions { }
                  }
                }
              }
            }
          }
